version: 2
defaults: &defaults
    working_directory: ~/ARMmbed/java-coap

    steps:
    - checkout

    # Restore the dependency cache
    - restore_cache:
        key: mbed-java-coap

    # Build and test
    - run: mvn install -P ci

    # Save dependency cache
    - save_cache:
        key: mbed-java-coap
        paths:
        - ~/.m2


    # publish coverage
    - run: bash <(curl -s https://codecov.io/bash)
    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
        when: always
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit

jobs:
  java-8:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    <<: *defaults


  java-11:
    docker:
    - image: circleci/openjdk:11-jdk-browsers
    <<: *defaults


workflows:
  version: 2
  commit:
    jobs:
      - java-8
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - java-8
      - java-11
  nightly-java7-backport:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - java7-backport
    jobs:
      - java-8
